import Link from "next/link";
import {ArrowLeft,ArrowRight,BookOpen,CalendarDays,ChevronRight,Clock,Code2,Play,Search,Users} from "lucide-react";

const tracks=[["AI & Data","Explore practical AI concepts and experiments.","8 courses","2h 40m"],["Software Development","Build interfaces, products, and useful tools.","12 courses","6h 10m"],["Cloud","Understand modern infrastructure and cloud systems.","6 courses","3h 25m"],["Cybersecurity","Learn foundations of secure digital systems.","7 courses","4h 05m"]];
const courses=[["Applied AI Foundations","AI & Data","8 lessons · 2h 40m · Beginner"],["Modern Web Builder","Software Development","10 lessons · 3h 15m · Intermediate"],["Cloud Concepts, Clearly","Cloud","7 lessons · 2h 05m · Beginner"],["Cybersecurity Essentials","Cybersecurity","9 lessons · 3h 20m · Beginner"],["Python for Projects","Software Development","12 lessons · 4h 10m · Beginner"],["Computer Vision Basics","AI & Data","8 lessons · 2h 55m · Intermediate"]];
const events=[["18","Oct","Build Night: From idea to prototype","MNU · Demo event"],["02","Nov","AI Builders Meetup","MNU · Demo event"],["16","Nov","Git & Open Source Night","MNU · Demo event"]];
const projects=[["VisionLab","Computer vision experiments for students.","Python · OpenCV · AI"],["CampusOS","A student-focused digital community concept.","Next.js · TypeScript"],["MedTech Monitor","A prototype for visualizing biomedical signals.","Python · Data"]];
const opportunities=[["Campus AI Challenge","Hackathon","Oct 24"],["Student Cloud Sprint","Competition","Nov 02"],["Open Source Starter Week","Community","Nov 16"]];
const lessons=["Welcome & the AI landscape","Thinking in models","Prompting as a design skill","Working with structured output","A small AI experiment","Evaluating what you build","Responsible use","Next steps"];

function Arrow(){return <ArrowRight className="arrow" size={16}/>}

function PageHero({label,title,lede,visual=true}:{label:string,title:string,lede:string,visual?:boolean}){
 return <div className="page-hero"><div className="page-hero-copy"><div className="breadcrumbs"><Link href="/">Home</Link><ChevronRight size={14}/><span>{label}</span></div><span className="eyebrow blue">MCC MNU</span><h1 className="page-title">{title}</h1><p className="page-lede">{lede}</p></div>{visual&&<div className="page-visual" aria-hidden="true"/>}</div>
}
function TileList({items,kind}:{items:string[][],kind:"course"|"project"}){
 return <div className="tile-grid">{items.map((x,i)=><Link className="tile" href={kind==="course"?"/courses/applied-ai-foundations":"/projects/visionlab"} key={x[0]}><div className="tile-art"/><span className="eyebrow blue">{x[1]||"Demo content"}</span><h3>{x[0]}</h3><p>{x[2]}</p><span className="tile-meta">{kind==="course"?"View course":"View project"} <Arrow/></span></Link>)}</div>
}
function Tracks(){
 return <div className="page"><PageHero label="Tracks" title="Explore learning paths." lede="Choose a direction, then follow a clear path through courses and lessons. Learning stays lightweight and practical."/><section className="content-section"><div className="path-list">{tracks.map((t,i)=><Link className="path-row" href="/tracks/ai-data" key={t[0]}><span className="path-icon">{i===0?<BookOpen size={19}/>:i===1?<Code2 size={19}/>:<Users size={19}/>}</span><div><h3>{t[0]}</h3><p>{t[1]}</p></div><div className="path-meta">{t[2]}<br/>{t[3]}</div><ChevronRight size={18}/></Link>)}</div></section></div>
}
function Courses(){
 return <div className="page"><PageHero label="Courses" title="Learn with MCC MNU." lede="Find focused courses and lessons designed to help you learn at your own pace."/><section className="content-section"><div className="search-box"><input aria-label="Search courses" placeholder="Search courses"/><button aria-label="Search"><Search size={18}/></button></div><div className="filters"><button className="filter active">All</button><button className="filter">AI & Data</button><button className="filter">Development</button><button className="filter">Cloud</button><button className="filter">Beginner</button></div><TileList items={courses} kind="course"/></section></div>
}
function Course(){
 return <div className="page"><PageHero label="Courses / Applied AI Foundations" title="Applied AI Foundations." lede="A practical introduction to modern AI. Learn the mental models, experiment with tools, and understand what good AI-assisted work looks like."/><div className="detail-grid"><section><h2>About this course</h2><p className="page-lede">This demo course is structured like a lightweight learning path: short lessons, useful resources, and a clear next step after every lesson.</p><h2 style={{marginTop:55}}>Course contents</h2><div className="info-list">{lessons.map((l,i)=><Link className="info-row" href={"/courses/applied-ai-foundations/lessons/"+(i===0?"introduction":"lesson-"+(i+1))} key={l}><span className="info-num">0{i+1}</span><div><h3>{l}</h3><small>{i===0?"08:40":"18:20"} · Video lesson</small></div><ChevronRight size={17}/></Link>)}</div></section><aside className="aside"><h3>Start learning</h3><p>8 lessons · 2h 40m · Beginner</p><Link className="primary" href="/courses/applied-ai-foundations/lessons/introduction">Start course <Arrow/></Link><h3 style={{marginTop:35}}>Skills</h3><p>AI fundamentals · structured prompting · evaluation · responsible use</p><div className="notice">Demo mode — progress is local and no account is connected.</div></aside></div></div>
}
function Lesson(){
 return <div className="video-page"><div className="breadcrumbs"><Link href="/">Home</Link><ChevronRight size={14}/><Link href="/courses">Courses</Link><ChevronRight size={14}/><span>Lesson 01</span></div><div className="video-layout"><div><div className="player"><button className="play-button" aria-label="Play demo video"><Play fill="currentColor" size={25}/></button></div><div className="video-info"><span className="eyebrow blue">Lesson 01 of 08 · Applied AI Foundations</span><h1>Welcome & the AI landscape</h1><p>This demo lesson introduces the course and sets expectations for a lightweight, practical learning experience.</p><div className="resource-row"><span className="filter">Lesson resources</span><span className="filter">Transcript</span><span className="filter">Notes</span></div><div className="notice">Demo video. Production video security and storage will be connected after MCC requirements are finalized.</div><div className="hero-actions"><Link className="secondary" href="/courses/applied-ai-foundations"><ArrowLeft size={16}/> Course</Link><Link className="primary" href="/courses/applied-ai-foundations/lessons/lesson-2">Next lesson <Arrow/></Link></div></div></div><aside className="lesson-sidebar"><h3>Course contents</h3>{lessons.map((x,i)=><Link className={"info-row "+(i===0?"current":"")} href="/courses/applied-ai-foundations/lessons/introduction" key={x}><span className="info-num">0{i+1}</span><div><h3>{x}</h3><small>{i===0?"08:40":"18:20"}</small></div></Link>)}</aside></div></div>
}
function Feedback(){
 return <div className="page"><PageHero label="Feedback" title="Tell us what you think." lede="Your feedback is anonymous and helps MCC improve future learning experiences."/><section className="feedback-shell"><div className="notice" style={{marginBottom:18}}>Demo mode — feedback infrastructure will be connected after MCC requirements are finalized.</div>{["Overall usefulness","Instructor clarity","Difficulty","Video engagement","Resources","Would recommend"].map(q=><div className="feedback-question" key={q}><h2>{q}</h2><div className="choice-row">{["1","2","3","4","5"].map(x=><button className="choice" key={x}>{x}</button>)}</div></div>)}<div className="feedback-question"><h2>Tell us more.</h2><label>What did you like?<textarea className="input" rows={4} placeholder="What worked well?"/></label><label>What could improve?<textarea className="input" rows={4} placeholder="What would make this better?"/></label><label>What should be added?<textarea className="input" rows={4} placeholder="Tell us what you want next."/></label><button className="primary">Submit anonymously <Arrow/></button></div></section></div>
}
function Events(){
 return <div className="page"><PageHero label="Events" title="What's happening at MCC." lede="Explore community sessions, build nights and other events. Demo content is clearly marked."/><section className="content-section"><div className="event-feature"><div className="event-date"><strong>18</strong><span>October</span></div><div className="event-copy"><span className="eyebrow" style={{color:"#fff"}}>Upcoming · Demo event</span><h3>Build Night: From idea to prototype</h3><p>Bring an idea, meet other builders, and leave with a clearer next step.</p></div><div className="event-cta"><Link className="secondary" href="/events/build-night">View event <Arrow/></Link></div></div><div className="event-list">{events.slice(1).map(e=><Link className="event-row" href="/events/build-night" key={e[2]}><time>{e[0]} {e[1]}</time><div><h3>{e[2]}</h3><p>{e[3]}</p></div><span className="event-type">Demo event</span><Arrow/></Link>)}</div></section></div>
}
function Projects(){
 return <div className="page"><PageHero label="Projects" title="See what students are building." lede="A developer-showcase view for student projects, experiments and prototypes."/><section className="content-section"><div className="feature-project"><div className="project-media"/><div className="project-copy"><span className="eyebrow" style={{color:"#8fd8ff"}}>Featured · Demo content</span><h3>VisionLab</h3><p>Computer vision experiments for students.</p><div className="tech-list"><span className="tech">Python</span><span className="tech">OpenCV</span><span className="tech">AI</span></div><Link className="text-link" style={{color:"#8fd8ff"}} href="/projects/visionlab">View project <Arrow/></Link></div></div><div style={{marginTop:18}}><TileList items={projects.slice(1)} kind="project"/></div></section></div>
}
function Opportunities(){
 return <div className="page"><PageHero label="Opportunities" title="Find your next opportunity." lede="A simple directory for challenges, competitions and community opportunities."/><section className="content-section"><div className="opportunity-list">{opportunities.map(o=><Link className="op-row" href="/opportunities" key={o[0]}><strong>{o[0]}</strong><span>{o[1]}</span><span>{o[2]}</span><span className="arrow-cell"><Arrow/></span></Link>)}</div></section></div>
}
function Resources(){
 const rs=[["Microsoft Learn","Learning","Use Microsoft Learn as a reference for technical concepts and guided training."],["GitHub","Development","Explore repositories, documentation and open-source workflows."],["Fluent 2","Design","Reference Microsoft's design language and interface patterns."],["MCC learning resources","MCC MNU","A future home for approved MCC materials and links."]];
 return <div className="page"><PageHero label="Resources" title="Resources for learning and building." lede="A documentation-style place for useful links, tools and references."/><section className="content-section"><div className="tile-grid">{rs.map(r=><div className="tile" key={r[0]}><span className="eyebrow blue">{r[1]}</span><h3>{r[0]}</h3><p>{r[2]}</p><span className="tile-meta">Learn more <Arrow/></span></div>)}</div></section></div>
}
function About(){return <div className="page"><PageHero label="About" title="More than a club." lede="MCC MNU is presented here as a student technology community experience focused on learning, building and connecting. Replace demo copy with approved MCC information when finalized."/><section className="content-section"><div className="value-row"><div className="value-item"><span className="value-number">01</span><h3>Community</h3><p>Meet students with different interests and complementary skills.</p></div><div className="value-item"><span className="value-number">02</span><h3>Learning</h3><p>Short, useful learning experiences organized by track and course.</p></div><div className="value-item"><span className="value-number">03</span><h3>Building</h3><p>Turn knowledge into projects, experiments and opportunities.</p></div></div></section></div>}
function Join(){return <div className="page"><PageHero label="Join" title="Join MCC MNU." lede="A presentation-only recruitment flow. Nothing is submitted or stored in this frontend prototype."/><section className="feedback-shell"><label>Name<input className="input" placeholder="Your name"/></label><label>Email<input className="input" placeholder="you@example.com"/></label><label>What interests you?<textarea className="input" rows={5} placeholder="Tell MCC what you want to learn or build."/></label><button className="primary">Apply to MCC <Arrow/></button><div className="notice">Demo mode — this form has no submission backend.</div></section></div>}
function Dashboard(){return <div className="page"><div className="dashboard-hero"><span className="eyebrow" style={{color:"#9edcff"}}>Demo student experience</span><h1 className="page-title">Welcome back.</h1><p>Continue learning, see what's next, and pick up where you left off.</p></div><div className="dashboard-grid"><div className="dash-main"><span className="eyebrow blue">Continue learning</span><h2>Applied AI Foundations</h2><p className="muted">Lesson 01 · 08:40 remaining</p><div className="progress"><span style={{width:"65%"}}/></div><Link className="primary" href="/courses/applied-ai-foundations/lessons/introduction">Continue <Arrow/></Link></div><div className="dash-side"><span className="eyebrow blue">Upcoming event</span><h3>Build Night</h3><p className="muted">18 October · MNU</p><Link className="text-link" href="/events">View events <Arrow/></Link></div></div><section className="content-section"><h2>Recommended learning</h2><TileList items={courses.slice(0,3)} kind="course"/></section></div>}
function Detail({type}:{type:"track"|"event"|"project"|"opportunity"}){
 const config=type==="track"?["AI & Data","Explore practical AI concepts and experiments.","8 courses · 2h 40m"]:type==="event"?["Build Night: From idea to prototype","Bring an idea, meet other builders, and leave with a clearer next step.","18 October · MNU"]:type==="project"?["VisionLab","Computer vision experiments for students.","Python · OpenCV · AI"]:["Campus AI Challenge","A demo opportunity directory entry.","Hackathon · Oct 24"];
 return <div className="page"><PageHero label={type} title={config[0]} lede={config[1]}/><div className="detail-grid"><section><h2>About this experience</h2><p className="page-lede">{config[1]} This presentation structure is ready for approved MCC content, imagery, people, dates and requirements.</p><div className="info-list"><div className="info-row"><BookOpen size={19}/><div><h3>Demo content</h3><small>{config[2]}</small></div></div><div className="info-row"><CalendarDays size={19}/><div><h3>Details to be confirmed</h3><small>Replace with approved information.</small></div></div></div></section><aside className="aside"><h3>Get involved</h3><p>Presentation-only flow. No production submission or registration is connected.</p><Link className="primary" href="/join">Join MCC <Arrow/></Link></aside></div></div>
}
export default async function Page({params}:{params:Promise<{segments:string[]}>}){
 const s=(await params).segments||[];const key=s.join("/");
 if(key==="about")return <About/>;if(key==="tracks")return <Tracks/>;if(key.startsWith("tracks/"))return <Detail type="track"/>;if(key==="courses")return <Courses/>;if(key.startsWith("courses/")&&s.length===2)return <Course/>;if(key.startsWith("courses/")&&s.length>=4)return <Lesson/>;if(key==="events")return <Events/>;if(key.startsWith("events/"))return <Detail type="event"/>;if(key==="projects")return <Projects/>;if(key.startsWith("projects/"))return <Detail type="project"/>;if(key==="opportunities")return <Opportunities/>;if(key.startsWith("opportunities/"))return <Detail type="opportunity"/>;if(key==="resources")return <Resources/>;if(key==="join")return <Join/>;if(key==="demo/dashboard")return <Dashboard/>;return <div className="page container"><h1 className="page-title">Page not found</h1><Link className="primary" href="/">Back home</Link></div>
}
