import Link from "next/link";
import {ArrowRight,BookOpen,Code2,Cloud,ShieldCheck} from "lucide-react";
const learning=[["Applied AI Foundations","AI & Data","8 lessons · 2h 40m · Beginner"],["Modern Web Builder","Software Development","10 lessons · 3h 15m · Intermediate"],["Cloud Concepts, Clearly","Cloud","7 lessons · 2h 05m · Beginner"]];
const paths=[["AI & Data","Explore practical AI concepts and experiments.","8 courses","2h 40m"],["Software Development","Build interfaces, products, and useful tools.","12 courses","6h 10m"],["Cloud","Understand modern infrastructure and cloud systems.","6 courses","3h 25m"],["Cybersecurity","Learn foundations of secure digital systems.","7 courses","4h 05m"]];
const events=[["18","Oct","Build Night: From idea to prototype","MNU · Demo event"],["02","Nov","AI Builders Meetup","MNU · Demo event"],["16","Nov","Git & Open Source Night","MNU · Demo event"]];
const opportunities=[["Campus AI Challenge","Hackathon","Oct 24"],["Student Cloud Sprint","Competition","Nov 02"],["Open Source Starter Week","Community","Nov 16"]];
function Arrow(){return <ArrowRight className="arrow" size={17}/>};
function PosterVisual(){return <div className="mcc-poster" aria-label="MCC MNU technology campaign visual"><div className="poster-noise"/><div className="poster-photo"><div className="poster-person"/><div className="poster-laptop"><div className="poster-screen"><i/><i/><i/><i/></div></div></div><div className="poster-cyan-block"><span>MCC MNU</span><strong>LEARN<br/>BUILD<br/>CONNECT</strong></div><div className="poster-copy"><span>MICROSOFT CAMPUS CLUB</span><strong>Ideas into<br/>working projects.</strong></div><div className="poster-cross poster-cross-a"/><div className="poster-cross poster-cross-b"/><div className="poster-index">01 / MCC MNU</div></div>};
function Mark({n}:{n:string}){return <span className="editorial-mark">{n}</span>};
export default function Home(){return <>
<section className="mcc-hero"><div className="mcc-hero-copy"><div className="mcc-kicker"><span className="mcc-kicker-line"/>MCC MNU · MICROSOFT CAMPUS CLUB</div><h1>Learn.<br/><span>Build.</span><br/>Connect.</h1><p>Technology learning, student projects, events and opportunities — presented in one place for the MCC MNU community.</p><div className="campaign-actions"><Link className="mcc-primary" href="/courses">Explore learning <Arrow/></Link><Link className="mcc-outline-link" href="/join">Join MCC <Arrow/></Link></div><div className="hero-meta"><span>01</span><span>Student technology community</span><span>Mansoura National University</span></div></div><PosterVisual/></section>
<section className="mcc-intro"><div className="container mcc-intro-grid"><div><Mark n="01"/><span className="mcc-section-label">THE MCC EXPERIENCE</span><h2>A technology community with a visual identity of its own.</h2></div><div className="mcc-intro-copy"><p>MCC MNU brings learning, building and community together. This presentation prototype turns the energy of MCC's promotional campaigns into a digital experience.</p><Link className="mcc-text-link" href="/about">Discover MCC <Arrow/></Link></div></div><div className="container mcc-strip"><span>LEARN</span><i/><span>BUILD</span><i/><span>CONNECT</span><i/><span>MCC MNU</span></div></section>
<section className="mcc-learning"><div className="container"><div className="mcc-heading"><div><Mark n="02"/><span className="mcc-section-label">LEARNING</span><h2>Go from curious to capable.</h2></div><Link className="mcc-text-link" href="/courses">View courses <Arrow/></Link></div><div className="mcc-learning-feature"><div className="mcc-learning-poster"><div className="poster-grid"/><span>FEATURED COURSE</span><strong>APPLIED<br/>AI<br/><em>FOUNDATIONS</em></strong><small>8 LESSONS · 2H 40M · BEGINNER</small><div className="poster-code">AI / DATA / BUILD</div></div><div className="mcc-learning-copy"><span className="mcc-blue-label">DEMO CONTENT</span><h3>Learn through focused lessons, not noise.</h3><p>Short video lessons, useful resources and a clear path from one concept to the next.</p><Link className="mcc-text-link" href="/courses/applied-ai-foundations">Start learning <Arrow/></Link></div></div><div className="mcc-learning-list">{learning.slice(1).map((c,i)=><Link href="/courses/applied-ai-foundations" className="mcc-list-item" key={c[0]}><span className="list-number">0{i+2}</span><div><span>{c[1]}</span><strong>{c[0]}</strong><small>{c[2]}</small></div><Arrow/></Link>)}<Link href="/tracks" className="mcc-list-item mcc-list-accent"><span className="list-number">+</span><div><span>MCC MNU</span><strong>Explore learning paths</strong><small>Tracks, courses and lessons</small></div><Arrow/></Link></div></div></section>
<section className="mcc-paths"><div className="container"><div className="mcc-heading"><div><Mark n="03"/><span className="mcc-section-label">LEARNING PATHS</span><h2>Choose a direction.</h2></div><Link className="mcc-text-link" href="/tracks">All tracks <Arrow/></Link></div><div className="mcc-path-grid">{paths.map((p,i)=><Link className="mcc-path" href="/tracks/ai-data" key={p[0]}><span className="mcc-path-number">0{i+1}</span><div className="mcc-path-icon">{i===0?<BookOpen size={22}/>:i===1?<Code2 size={22}/>:i===2?<Cloud size={22}/>:<ShieldCheck size={22}/>}</div><h3>{p[0]}</h3><p>{p[1]}</p><div className="mcc-path-meta">{p[2]} · {p[3]} <Arrow/></div></Link>)}</div></div></section>
<section className="mcc-projects"><div className="container"><div className="mcc-heading mcc-heading-dark"><div><Mark n="04"/><span className="mcc-section-label">PROJECTS</span><h2>Build something real.</h2></div><Link className="mcc-text-link-light" href="/projects">View projects <Arrow/></Link></div><div className="mcc-project-feature"><div className="mcc-project-visual"><div className="project-scanline"/><div className="project-ui"><span>COMPUTER VISION</span><strong>VisionLab</strong><small>PYTHON · OPENCV · AI</small></div><div className="project-corner">MCC / 04</div></div><div className="mcc-project-copy"><span className="mcc-blue-label">DEMO PROJECT</span><h3>Ideas should leave the screen.</h3><p>VisionLab is a presentation project exploring computer vision experiments and practical AI workflows.</p><Link className="mcc-text-link-light" href="/projects/visionlab">View project <Arrow/></Link></div></div><div className="mcc-project-links"><Link href="/projects/campusos">CampusOS <Arrow/></Link><Link href="/projects/medtech-monitor">MedTech Monitor <Arrow/></Link><Link href="/projects">All projects <Arrow/></Link></div></div></section>
<section className="mcc-events"><div className="container"><div className="mcc-heading"><div><Mark n="05"/><span className="mcc-section-label">EVENTS & WORKSHOPS</span><h2>Meet. Make. Share.</h2></div><Link className="mcc-text-link" href="/events">All events <Arrow/></Link></div><div className="mcc-event-feature"><div className="mcc-event-date"><span>OCT</span><strong>18</strong><small>2026</small></div><div className="mcc-event-copy"><span className="mcc-blue-label">DEMO EVENT · MNU</span><h3>Build Night:<br/>From idea to prototype.</h3><p>Bring an idea, meet other builders and leave with a clearer next step.</p><Link className="mcc-primary" href="/events/build-night">View event <Arrow/></Link></div><div className="mcc-event-poster"><span>WORKSHOP</span><strong>BUILD<br/>NIGHT</strong><small>MCC MNU</small></div></div><div className="mcc-event-list">{events.slice(1).map((e,i)=><Link className="mcc-event-row" href="/events/build-night" key={e[2]}><span>0{i+2}</span><time>{e[0]} {e[1]}</time><div><strong>{e[2]}</strong><small>{e[3]}</small></div><Arrow/></Link>)}</div></div></section>
<section className="mcc-community"><div className="container mcc-community-grid"><div className="mcc-community-art"><div className="community-photo-placeholder"><div className="community-person community-person-a"/><div className="community-person community-person-b"/><div className="community-screen"/></div><span className="community-stamp">MCC MNU<br/>COMMUNITY</span></div><div className="mcc-community-copy"><Mark n="06"/><span className="mcc-section-label">COMMUNITY</span><h2>Find people to learn and build with.</h2><p>Explore events, projects, learning and opportunities — then find your place in the MCC MNU community.</p><Link className="mcc-text-link" href="/join">Get involved <Arrow/></Link></div></div></section>
<section className="mcc-opportunities"><div className="container"><div className="mcc-heading"><div><Mark n="07"/><span className="mcc-section-label">OPPORTUNITIES</span><h2>What's next?</h2></div><Link className="mcc-text-link" href="/opportunities">Explore opportunities <Arrow/></Link></div><div className="mcc-op-list">{opportunities.map((o,i)=><Link className="mcc-op-row" href="/opportunities" key={o[0]}><span>0{i+1}</span><strong>{o[0]}</strong><em>{o[1]}</em><time>{o[2]}</time><Arrow/></Link>)}</div></div></section>
<section className="mcc-join"><div className="container mcc-join-inner"><div><span className="mcc-section-label light-label">MCC MNU</span><h2>Make your next project matter.</h2><p>Learn something useful. Build something real. Meet the people who will build it with you.</p></div><Link className="mcc-join-button" href="/join">Join MCC MNU <Arrow/></Link></div></section>
<footer className="mcc-footer"><div className="container mcc-footer-grid"><div><div className="mcc-footer-brand">MCC <span>MNU</span></div><p>Microsoft Campus Club · Mansoura National University</p></div><div><h3>LEARN</h3><Link href="/courses">Courses</Link><Link href="/tracks">Tracks</Link><Link href="/resources">Resources</Link></div><div><h3>BUILD</h3><Link href="/projects">Projects</Link><Link href="/events">Events</Link><Link href="/opportunities">Opportunities</Link></div><div><h3>CONNECT</h3><Link href="/about">About MCC</Link><Link href="/join">Join MCC</Link><Link href="/demo/dashboard">Student experience</Link></div></div><div className="container mcc-footer-bottom"><span>© MCC MNU · Presentation prototype</span><span>Demo content is clearly marked where applicable.</span></div></footer>
</>}